In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pyarrow
from pathlib import Path
import scipy
from scipy import stats
from scipy.stats import pearsonr, spearmanr

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
sns.set_theme(style='whitegrid')

plt.rcParams['figure.figsize'] = (10, 6)

In [5]:
import sqlite3
conn = sqlite3.connect("../data/raw/ecommerce.db")

In [7]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

       name
0  2019-Oct
1  2019-Nov
2  2019-Dec
3  2020-Jan
4  2020-Feb

In [10]:
pd.read_sql('PRAGMA table_info("2019-Oct");', conn)

   cid           name    type  notnull dflt_value  pk
0    0          index  BIGINT        0       None   0
1    1     event_time    TEXT        0       None   0
2    2     event_type    TEXT        0       None   0
3    3     product_id  BIGINT        0       None   0
4    4    category_id  BIGINT        0       None   0
5    5  category_code    TEXT        0       None   0
6    6          brand    TEXT        0       None   0
7    7          price   FLOAT        0       None   0
8    8        user_id  BIGINT        0       None   0
9    9   user_session    TEXT        0       None   0

In [ ]:
dec19 = pd.read_sql('SELECT * FROM "2019-Oct";', conn)

DatabaseError: Execution failed on sql '2019-Oct': near "2019": syntax error